# 
# SUMMARY: Pipeline to a deploy shared services (Resource Group, Storage Account, KeyVault) for given params.
# DESCRIPTION: The following components will be required parameters in this deployment
#     resourcegroupname
#     location
#     storageaccountparamfilename
#     keyvaultparamfilename
#     subscriptionName - Requires an ARM service connection
# AUTHOR/S: asaikovski
# VERSION: 1.0.0
# VERSION HISTORY:  
#  1.0.0 - Initial creation
name: 'Deploy Shared Services - Resource Group, Storage Account & KeyVault'
parameters:
- name: resourcegroupname
  displayName: Resource Group Name
  type: string
  default: 'tcp-sharedresources-ase-rg'
- name: location
  displayName: Resource Location
  type: string
  default: 'australiasoutheast'
  values:
  - 'australiasoutheast'
  - 'australiaeast'
- name: storageaccountparamfilename
  displayName: Storage Account Input Parameter Filename (VMs/filename.bicep)
  type: string
  default: 'storageAccounts/storageAccount-dev-parameters.bicep'
- name: keyvaultparamfilename
  displayName: Keyvault Input Parameter Filename (VMs/filename.bicep)
  type: string
  default: 'KeyVault/keyVault-dev-parameters.bicep'
- name: keyvaultsecretname
  displayName: Keyvault Secret Name to create in KeyVault
  type: string
  default: 'KeyVaultSecretName'
- name: subscriptionName
  displayName: Target Subscription
  type: string
  default: 'Telstra POC Test'
trigger:
- none
pool:
  vmImage: 'ubuntu-latest'
variables:
- name: secretInput
- name: adminPassword
steps:
- task: AzureCLI@2
  displayName: 'Create Resource Group.'
  inputs:
    azureSubscription: ${{ parameters.subscriptionName }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade --yes
      az bicep upgrade
      az group create \
              --name ${{ parameters.resourcegroupname }} \
              --location ${{ parameters.location }} 
- task: AzureCLI@2
  displayName: 'Provision Shared Storage Account.'
  inputs:
    azureSubscription: ${{ parameters.subscriptionName }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade --yes
      az bicep upgrade
      az deployment group create --resource-group "${{ parameters.resourcegroupname }}" --template-file '$(Build.SourcesDirectory)/${{ parameters.storageaccountparamfilename }}'
- task: AzureCLI@2
  displayName: 'Provision KeyVault'
  inputs:
    azureSubscription: ${{ parameters.subscriptionName }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
       az upgrade --yes
       az bicep upgrade
       sudo apt install pwgen
       adminPassword=$(pwgen -c -n -s 13 1)
       secretInput="{\"secureList\":[{\"name\":\"${{ parameters.keyvaultsecretname }}\",\"value\":\"$adminPassword\"}]}" ##TODO find a better way to store this secret
       az deployment group create \
          --resource-group "${{ parameters.resourcegroupname }}" \
          --template-file '$(Build.SourcesDirectory)/${{ parameters.keyvaultparamfilename }}' \
          --parameters secrets=$secretInput